server:
   port: 8090
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/Products_Ms
      username: root
      password: 123456789
   jpa:
      properties:
         hibernate:
            show_sql: false
            format_sql: false
      database-platform: org.hibernate.dialect.MySQLDialect